// Export all components
export {AppRoot} from './app-root/app-root';
export {AppTabs} from './app-tabs/app-tabs';
export {CompressTab} from './compress-tab/compress-tab';
export {DecompressTab} from './decompress-tab/decompress-tab';
export {DocsTab} from './docs-tab/docs-tab';
export {FileDropzone} from './file-dropzone/file-dropzone';
export {HealthIndicator} from './health-indicator/health-indicator';
export {ProgressBar} from './progress-bar/progress-bar';
