/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TabType } from "./components/app-tabs/app-tabs";
export { TabType } from "./components/app-tabs/app-tabs";
export namespace Components {
    interface AppRoot {
    }
    interface AppTabs {
        /**
          * @default 'docs'
         */
        "activeTab": TabType;
    }
    interface CompressTab {
    }
    interface DecompressTab {
    }
    interface DocsTab {
    }
    interface FileDropzone {
        "accept"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'or click to browse'
         */
        "hint": string;
        /**
          * @default '📄'
         */
        "icon": string;
        /**
          * @default 'Drop your file here'
         */
        "label": string;
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary';
    }
    interface HealthIndicator {
        /**
          * Polling interval in seconds (default: 30 seconds)
          * @default 30
         */
        "pollInterval": number;
        /**
          * Whether to show the last checked time (default: false)
          * @default false
         */
        "showLastChecked": boolean;
        /**
          * Whether to show the status text (default: true)
          * @default true
         */
        "showText": boolean;
    }
    interface ProgressBar {
        /**
          * @default true
         */
        "animated": boolean;
        /**
          * @default false
         */
        "complete": boolean;
        /**
          * @default ''
         */
        "phase": string;
        /**
          * @default 0
         */
        "progress": number;
        /**
          * @default true
         */
        "showPercentage": boolean;
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary';
    }
}
export interface AppTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppTabsElement;
}
export interface FileDropzoneCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFileDropzoneElement;
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTabsElementEventMap {
        "tabChange": TabType;
    }
    interface HTMLAppTabsElement extends Components.AppTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppTabsElementEventMap>(type: K, listener: (this: HTMLAppTabsElement, ev: AppTabsCustomEvent<HTMLAppTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppTabsElementEventMap>(type: K, listener: (this: HTMLAppTabsElement, ev: AppTabsCustomEvent<HTMLAppTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppTabsElement: {
        prototype: HTMLAppTabsElement;
        new (): HTMLAppTabsElement;
    };
    interface HTMLCompressTabElement extends Components.CompressTab, HTMLStencilElement {
    }
    var HTMLCompressTabElement: {
        prototype: HTMLCompressTabElement;
        new (): HTMLCompressTabElement;
    };
    interface HTMLDecompressTabElement extends Components.DecompressTab, HTMLStencilElement {
    }
    var HTMLDecompressTabElement: {
        prototype: HTMLDecompressTabElement;
        new (): HTMLDecompressTabElement;
    };
    interface HTMLDocsTabElement extends Components.DocsTab, HTMLStencilElement {
    }
    var HTMLDocsTabElement: {
        prototype: HTMLDocsTabElement;
        new (): HTMLDocsTabElement;
    };
    interface HTMLFileDropzoneElementEventMap {
        "fileSelected": File;
        "fileCleared": void;
    }
    interface HTMLFileDropzoneElement extends Components.FileDropzone, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFileDropzoneElementEventMap>(type: K, listener: (this: HTMLFileDropzoneElement, ev: FileDropzoneCustomEvent<HTMLFileDropzoneElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFileDropzoneElementEventMap>(type: K, listener: (this: HTMLFileDropzoneElement, ev: FileDropzoneCustomEvent<HTMLFileDropzoneElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFileDropzoneElement: {
        prototype: HTMLFileDropzoneElement;
        new (): HTMLFileDropzoneElement;
    };
    interface HTMLHealthIndicatorElement extends Components.HealthIndicator, HTMLStencilElement {
    }
    var HTMLHealthIndicatorElement: {
        prototype: HTMLHealthIndicatorElement;
        new (): HTMLHealthIndicatorElement;
    };
    interface HTMLProgressBarElement extends Components.ProgressBar, HTMLStencilElement {
    }
    var HTMLProgressBarElement: {
        prototype: HTMLProgressBarElement;
        new (): HTMLProgressBarElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "app-tabs": HTMLAppTabsElement;
        "compress-tab": HTMLCompressTabElement;
        "decompress-tab": HTMLDecompressTabElement;
        "docs-tab": HTMLDocsTabElement;
        "file-dropzone": HTMLFileDropzoneElement;
        "health-indicator": HTMLHealthIndicatorElement;
        "progress-bar": HTMLProgressBarElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface AppTabs {
        /**
          * @default 'docs'
         */
        "activeTab"?: TabType;
        "onTabChange"?: (event: AppTabsCustomEvent<TabType>) => void;
    }
    interface CompressTab {
    }
    interface DecompressTab {
    }
    interface DocsTab {
    }
    interface FileDropzone {
        "accept"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'or click to browse'
         */
        "hint"?: string;
        /**
          * @default '📄'
         */
        "icon"?: string;
        /**
          * @default 'Drop your file here'
         */
        "label"?: string;
        "onFileCleared"?: (event: FileDropzoneCustomEvent<void>) => void;
        "onFileSelected"?: (event: FileDropzoneCustomEvent<File>) => void;
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary';
    }
    interface HealthIndicator {
        /**
          * Polling interval in seconds (default: 30 seconds)
          * @default 30
         */
        "pollInterval"?: number;
        /**
          * Whether to show the last checked time (default: false)
          * @default false
         */
        "showLastChecked"?: boolean;
        /**
          * Whether to show the status text (default: true)
          * @default true
         */
        "showText"?: boolean;
    }
    interface ProgressBar {
        /**
          * @default true
         */
        "animated"?: boolean;
        /**
          * @default false
         */
        "complete"?: boolean;
        /**
          * @default ''
         */
        "phase"?: string;
        /**
          * @default 0
         */
        "progress"?: number;
        /**
          * @default true
         */
        "showPercentage"?: boolean;
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary';
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "app-tabs": AppTabs;
        "compress-tab": CompressTab;
        "decompress-tab": DecompressTab;
        "docs-tab": DocsTab;
        "file-dropzone": FileDropzone;
        "health-indicator": HealthIndicator;
        "progress-bar": ProgressBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-tabs": LocalJSX.AppTabs & JSXBase.HTMLAttributes<HTMLAppTabsElement>;
            "compress-tab": LocalJSX.CompressTab & JSXBase.HTMLAttributes<HTMLCompressTabElement>;
            "decompress-tab": LocalJSX.DecompressTab & JSXBase.HTMLAttributes<HTMLDecompressTabElement>;
            "docs-tab": LocalJSX.DocsTab & JSXBase.HTMLAttributes<HTMLDocsTabElement>;
            "file-dropzone": LocalJSX.FileDropzone & JSXBase.HTMLAttributes<HTMLFileDropzoneElement>;
            "health-indicator": LocalJSX.HealthIndicator & JSXBase.HTMLAttributes<HTMLHealthIndicatorElement>;
            "progress-bar": LocalJSX.ProgressBar & JSXBase.HTMLAttributes<HTMLProgressBarElement>;
        }
    }
}
